# À propos des auteurs {#auteurs .unnumbered}

[**Philippe Apparicio**](https://www.usherbrooke.ca/recherche/fr/specialistes/details/philippe.apparicio) est professeur titulaire au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Il y enseigne aux [programmes de 1^er^ et 2^e^ cycles de géomatique](https://www.usherbrooke.ca/geomatique/etudes/programmes) les cours *Transport et mobilité durable*, *Modélisation et analyse spatiale* et *Géomatique appliquée à la gestion urbaine*. Durant les dernières années, il a offert plusieurs formations aux Écoles d'été du Centre interuniversitaire québécois de statistiques sociales ([CIQSS](https://www.ciqss.org/)). Géographe de formation, ses intérêts de recherche incluent la justice et l'équité environnementale, la mobilité durable, les pollutions atmosphérique et sonore, et le vélo en ville. Il a publié une centaine d'articles scientifiques dans différents domaines des études urbaines et de la géographie mobilisant la géomatique et l'analyse spatiale.

[**Yacine Bouroubi**](https://www.usherbrooke.ca/geomatique/departement/personnel/personnel-enseignant/yacine-bouroubi) est professeur titulaire au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Il y enseigne aux [programmes de 1^er^ et 2^e^ cycles de géomatique](https://www.usherbrooke.ca/geomatique/etudes/programmes) les cours *Transport et mobilité durable*, *Modélisation et analyse spatiale* et *Géomatique appliquée à la gestion urbaine*. Durant les dernières années, il a offert plusieurs formations aux Écoles d'été du Centre interuniversitaire québécois de statistiques sociales ([CIQSS](https://www.ciqss.org/)). Géographe de formation, ses intérêts de recherche incluent la justice et l'équité environnementale, la mobilité durable, les pollutions atmosphérique et sonore, et le vélo en ville. Il a publié une centaine d'articles scientifiques dans différents domaines des études urbaines et de la géographie mobilisant la géomatique et l'analyse spatiale.

[**Samuel Foucher**](https://www.usherbrooke.ca/recherche/fr/specialistes/details/samuel.foucher) est professeur titulaire au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Il y enseigne aux [programmes de 1^er^ et 2^e^ cycles de géomatique](https://www.usherbrooke.ca/geomatique/etudes/programmes) les cours *Transport et mobilité durable*, *Modélisation et analyse spatiale* et *Géomatique appliquée à la gestion urbaine*. Durant les dernières années, il a offert plusieurs formations aux Écoles d'été du Centre interuniversitaire québécois de statistiques sociales ([CIQSS](https://www.ciqss.org/)). Géographe de formation, ses intérêts de recherche incluent la justice et l'équité environnementale, la mobilité durable, les pollutions atmosphérique et sonore, et le vélo en ville. Il a publié une centaine d'articles scientifiques dans différents domaines des études urbaines et de la géographie mobilisant la géomatique et l'analyse spatiale.

[**Mickaël Germain**](https://www.usherbrooke.ca/geomatique/departement/personnel/personnel-enseignant/mickael-germain) est professeur titulaire au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Il y enseigne aux [programmes de 1^er^ et 2^e^ cycles de géomatique](https://www.usherbrooke.ca/geomatique/etudes/programmes) les cours *Transport et mobilité durable*, *Modélisation et analyse spatiale* et *Géomatique appliquée à la gestion urbaine*. Durant les dernières années, il a offert plusieurs formations aux Écoles d'été du Centre interuniversitaire québécois de statistiques sociales ([CIQSS](https://www.ciqss.org/)). Géographe de formation, ses intérêts de recherche incluent la justice et l'équité environnementale, la mobilité durable, les pollutions atmosphérique et sonore, et le vélo en ville. Il a publié une centaine d'articles scientifiques dans différents domaines des études urbaines et de la géographie mobilisant la géomatique et l'analyse spatiale.

